spring:
  application:
    name: weather-app-api

  # Data source configuration
  datasource:
    url: jdbc:sqlite:weatherapp.db
    driver-class-name: org.sqlite.JDBC

  # JPA configuration
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update

  # Required to access the H2 console
  h2:
    console:
      path: /h2-console
      enabled: true

  # Turn off the Spring Boot banner
  main:
    banner-mode: off

weather:
  api:
    base-url: https://wttr.in
    url-params: /%s?format=j1